spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MisakaMikoto2!
spring.jpa.properties.hibernate.default_schema=mbti
spring.security.user.name=Midax
spring.security.user.password=qwerty12345

jwt.private-key=classpath:jwt/app.key
jwt.public-key=classpath:jwt/app.pub
jwt.ttl=15m