# Spring Application
spring.application.name=Backend
server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}
app.client.url=${CLIENT_URL}
app.client.port=${CLIENT_PORT}
app.email.reset-password-url=http://${app.client.url}:${app.client.port}/reset-password?token=
app.email.confirm-email-url=http://${server.address}:${server.port}/api/auth/confirm-email?token=

# Spring Data Source
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=mbti

# Spring Security
spring.security.user.name=${SPRING_NAME}
spring.security.user.password=${SPRING_PASSWORD}

# Spring Session
server.servlet.session.cookie.name=MY_SESSION_COOKIE
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.tracking-modes=cookie
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.session.redis.save-mode=on-set-attribute

# Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Minio Configuration
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=user-profiles

# Spring Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB